### ISSUE TITLE
Generate new tests

### ISSUE THREAD

**Issue by constantinospas** [michaelthe/puppyjs#35]
Create a command so the user can create new tests using CLI. 
For example `$ puppy new test testname` should create a new file `testname.pup.js` in e2e folder with basic structure like
```
describe('description', () => {

  let page

  beforeEach(async () => {
    page = await puppy.newPage()
  })

  afterEach(async () => {
    await page.close()
  })

  it('should ', async function () {
     
  })

})

```

**Comment by pitops** [comment]
I am closing this issue for now until people start requesting for this.
