### ISSUE TITLE
How to use puppy serve with sockets?

### ISSUE THREAD

**Issue by BlackConure** [michaelthe/puppyjs#37]
I am looking to run puppyjs in serve mode using sockets.   

It seems that the current implementation allows puppy to emit messages, but I don't see how to configure puppyjs to listen for a message (as you can with the http api).   Is this possible?   If so, are there any examples?

**Comment by pitops** [comment]
Hi there @BlackConure at this point no its not supported yet. Its one way communication from puppyjs to the client only. But its a good suggestion, I will ping @michaelthe to discuss this.

**Comment by BlackConure** [comment]
As it turns out, I opened up the code and am adding it now.   If you are interested I can send you what I ended up with.   I am trying to keep it within your coding style...but obviously would need a more an eye of scrutiny to ensure that I don't hose things up.   :)

**Comment by pitops** [comment]
Awesome! Can you please create a pull request? :)

**Comment by pitops** [comment]
#38
